### PR TITLE
Move docs to pde

### PR DESCRIPTION
**Pull request by laeubi**
This is an attempt to move the `org.eclipse.pde.doc.user` from aggregator to the PDE project.

@mickaelistria I used your suggested workflow but it feels like this can not work with the previous merge of the repositories so some history seems lost.

### CODE REVIEW

**Comment by laeubi** [comment]
The build is green except usual Merge commit changes what is expected here.

**Comment by laeubi** [comment]
FYI I think I was able to recover more history here, the trick was to include the old path in the filter ...

**Comment by vogella** [comment]
Result looks fine to me, I did not check for Git history but I truest that @laeubi did.

**Comment by laeubi** [comment]
> I did not check for Git history but I truest that @laeubi did.

I think I now got a bit too much, will retry with a more strict filter... another approach of course would be to **not** include entire history, not sure how useful this is

**Comment by laeubi** [comment]
I updated the PR, history now looks fine to me, maybe someone else likes to approve.

**Comment by vogella** [comment]
Still looks fine to me, PDE project lead needs to allow merge commits. @HannesWell can you do this?

**Comment by laeubi** [comment]
@mickaelistria I see in the build log that the baseline compare is not executed for that project, can you help in enable it?

Beside that I noticed that the `/reference/api/` folder is empty after the build but got no error, how can one debug this? I assume some path has to be adjusted here.

**Comment by laeubi** [comment]
Before this can be merged I need to sort out the javadoc issues... so setting this to **draft**.

**Comment by HannesWell** [comment]
> Still looks fine to me, PDE project lead needs to allow merge commits. @HannesWell can you do this?

I don't know how to do that in detail, but I'm happy to approve anything related if someone requests it.

**Comment by laeubi** [comment]
Javadoc issue is addressed here:
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1501

will update the PR soon

**Comment by laeubi** [comment]
As we are late in the release I'll postpone this to 2024-03 ...

**Comment by laeubi** [comment]
This is now ready but should be merged before any other things in PDE (including version increments @MohananRahul ) as soon as we are allowed to push things to master and Milestones are published.

@HannesWell if you to the repos settings you can enable merge commits:

grafik

**Review by HannesWell — APPROVED** [review]
Thanks @laeubi this looks good.

Placing o.e.pde.doc.user in the root of the repo while other projects are located in sub-folders according to their topic seems not to be ideal, but I don't know a better location either (having a documentation/doc sub-folder for one project seems to be an overkill and I don't expect more in the near future).

> This is now ready but should be merged before any other things in PDE (including version increments @MohananRahul ) as soon as we are allowed to push things to master and Milestones are published.

I can see the `R4_30_maintenance` branch was created and I see no I-build scheduled for the next week in the [platform-calender](https://calendar.google.com/calendar/u/0/embed?src=prfk26fdmpru1mptlb06p0jh4s@group.calendar.google.com).
Therefore I assume it is save to merge this as a very first step now.

Nevertheless @MohananRahul or @akurtakov can you please confirm this?

> 
> @HannesWell if you to the repos settings you can enable merge commits:
> 

Merge commits are enabled.

**Comment by akurtakov** [comment]
Please merge, I don't see a reason to delay this anymore.

**Comment by laeubi** [comment]
@HannesWell merge commits can be disabled again.

**Comment by laeubi** [comment]
Corresponding PR for aggregator repo:

- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1575

**Comment by HannesWell** [comment]
Thanks Christoph. Very nice.


> @HannesWell merge commits can be disabled again.

Disabled again.

**Pull request merged**
