### PR TITLE
Simplify and clean-up API baseline initialization

### PR DESCRIPTION
**Pull request by HannesWell**
Also remove unused method ApiBaseline.getVisibleDependentComponents().

@merks you often looked into the API-baseline tooling. Do you want to review this?

I assume `ApiBaselineManager.createWorkspaceBaseline()` used to be so complicated because it grew historically.

### CODE REVIEW

**Comment by merks** [comment]
I've only tried to make the complicated stuff work when it's not working, not try to understand why it's so complicated...

**Comment by HannesWell** [comment]
> I've only tried to make the complicated stuff work when it's not working, not try to understand why it's so complicated...

Understand. Then I assume you are fine with this.

All tests pass, although I see that the GH workflows are not running...

**Comment by merks** [comment]
It sure bypasses a lot of stuff, but if you've tested it and the test pass, it definitely gets rid of a lot of complexity!!

**Comment by HannesWell** [comment]
> It sure bypasses a lot of stuff, but if you've tested it and the test pass, it definitely gets rid of a lot of complexity!!

In my local test (but I could only test a simple case) this worked well and all tests pass.

**Pull request merged**
