### PR TITLE
Use static Collection factories

### PR DESCRIPTION
**Pull request by HannesWell**
Searched for ".unmodifiable(" and "Arrays.asList(" to find suitable applications.

### CODE REVIEW

**Review by vogella — APPROVED** [review]
LGTM

**Comment by vogella** [comment]
IMHO calling contains(null) is an error in the usage of this API. So doing this commit early in 4.25 should help us identify bad users and fix them.

**Comment by merks** [comment]
> IMHO calling contains(null) is an error in the usage of this API. So doing this commit early in 4.25 should help us identify bad users and fix them.

That sounds like a scary comment to me.   I don't want to be a bad user, but do I have time to figure out what might be impacted by this so that I can add some special handling for null in cases that are just fine right now?

**Comment by vogella** [comment]
> > IMHO calling contains(null) is an error in the usage of this API. So doing this commit early in 4.25 should help us identify bad users and fix them.
> 
> That sounds like a scary comment to me. I don't want to be a bad user, but do I have time to figure out what might be impacted by this so that I can add some special handling for null in cases that are just fine right now?

Yes, Java API can be scary ;-) See https://docs.oracle.com/javase/8/docs/api/java/util/Collection.html#contains-java.lang.Object- It is specified that you get an NPE is you call contains with null.

**Comment by mickaelistria** [comment]
@HannesWell looks like some other version bumps are necessary.

**Comment by akurtakov** [comment]
What is the plan for this one? At the very minimum it needs manual rebase now.

**Comment by HannesWell** [comment]
> What is the plan for this one? At the very minimum it needs manual rebase now.

I want to complete this one. But IIRC there were some new test failures with the current state that needs to be fixed first.

**Comment by HannesWell** [comment]
For me this is ready now. Does anybody want to review this?

**Comment by akurtakov** [comment]
I see 350 failed tests not the usual 349 :) . I wonder which one would that be.

**Comment by HannesWell** [comment]
> I see 350 failed tests not the usual 349 :) . I wonder which one would that be.

It was `configureProjectAndCheckMarkers[20: OSGi EventAdmin Service Example] (org.eclipse.pde.ui.templates.tests.TestPDETemplates)` and I fixed it.
The previously used HashSet contained null as valid value and since the statically created sets don't permit null it has to be checked separately. When checking the code again yesterday I didn't remember that `null` used to be a value contained in the set and assumed the null check was only to guard against passing null to the contains method of the static-set. But that was a false assumpption and I reverted that.

Nevertheless I wonder why this test did not fail in Jenkins?

**Comment by HannesWell** [comment]
I plan to submit this once the master branch opens again.

**Comment by HannesWell** [comment]
Besides the Windows GH workflow (which seems to have some FS issues), all builds are green, thus submitting.

**Pull request merged**
