### PR TITLE
Less question mark icons in confirmation dialogs

### PR DESCRIPTION
**Pull request by vogella**

### CODE REVIEW

**Review by vogella — COMMENTED** [review]
NOT YET READY

**Comment by HannesWell** [comment]
> NOT YET READY

You can also create a PR as draft (or later convert it to one):
https://github.blog/2019-02-14-introducing-draft-pull-requests/

That should also make it clear that it is not yet ready.

**Comment by vogella** [comment]
> > NOT YET READY
> 
> You can also create a PR as draft (or later convert it to one): https://github.blog/2019-02-14-introducing-draft-pull-requests/
> 
> That should also make it clear that it is not yet ready and it cannot be merged (unless a committer marks it as "Read for review").

Cool, thanks for the information.

**Comment by vogella** [comment]
Looks fine to me

image

**Pull request merged**
