### PR TITLE
Deadlock in API tooling after removing projects from workspace

### PR DESCRIPTION
**Pull request by iloveeclipse**
Makes workspace baseline disposal task to job and makes sure it doesn't run in parallel with API analysis jobs.

Fixes https://github.com/eclipse-pde/eclipse.pde/issues/1088

### CODE REVIEW

**Comment by iloveeclipse** [comment]
@laeubi : quality gate is finding 2 maven warnings that weren't introduced by this PR.
So I assume I have to ignore that as usually with all maven warnings, or is this a problem that need to be reported somewhere?

**Comment by laeubi** [comment]
I have not yet find out why baseline errors are reported here, it seems always one or two items but I can't reproduce it locally.

If you have an idea what can causing this (it is always the same project and always the same file) that would be helpfull but for this PR I think we can't fix it see:

- https://github.com/eclipse-pde/eclipse.pde/pull/1080

beside that PDE should normally show zero maven warnings.

**Comment by iloveeclipse** [comment]
> If you have an idea what can causing this

Sorry, no idea about Maven / tycho in general and for the particular warnings in particular. I guess some maven/tycho specific parameters in Jenkinsfile that makes Jenkins execution differ from the official SDK build, but honestly no idea which one.

**Comment by laeubi** [comment]
> Sorry, no idea about Maven / tycho in general and for the particular warnings in particular.

The warning basically says that baseline compile result does not match verification compile result I have created
- https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1921

with compiler logs and baseline versus compile results.

**Pull request merged**
