### PR TITLE
Pde build merge

### PR DESCRIPTION
**Pull request by vogella**

### CODE REVIEW

**Comment by vogella** [comment]
@vik-chand and @HannesWell can you do a sanity check? Basically pde will have one additional starting commit and all commits from pde build master branch are available in the pde.ui.

**Comment by iloveeclipse** [comment]
@vogella : Somehow I'm unable to see recent pde build commits in this PR. Are you sure your repo was up-to-date with master?

**Comment by iloveeclipse** [comment]
OK, I had toggled "show first parent only" which simplifies display of merged branches.
One point missing: no tags are preserved at all for pde build. means, you can't see which commit was in which build / milestone / release.

image

**Comment by vogella** [comment]
> One point missing: no tags are preserved at all for pde build. means, you can't see which commit was in which build / milestone / release.

Can I add tags as part of a PR? Does not look like it to me. Once this is merged, I could push the tags from pde.build to pde.ui if that is desired. Not sure if we want that, the commits in the new repo were not the onces placed in the buid, it was from the old repo.

**Review by HannesWell — COMMENTED** [review]
> @vik-chand and @HannesWell can you do a sanity check? Basically pde will have one additional starting commit and all commits from pde build master branch are available in the pde.ui.

The Git-History looks good.
I think it would be good to rebase on the Aleks latest change, otherwise it has to be squashed and merged.

What's IMHO missing is 
- [ ] move the plug-ins into a sub-folder, what do you think about `build`?
- [ ] The Oomph setup has to be adjusted.

Do you want to do that with this PR or in a follow up?

**Comment by vogella** [comment]
I can redo the merge work but would like to get confirmation from @vik-chand that he is fine with the merged history. @vik-chand can you check?

**Comment by HannesWell** [comment]
> I can redo the merge work but would like to get confirmation from @vik-chand that he is fine with the merged history. @vik-chand can you check?

Thanks! Makes sense.
Please note that I added another commit to pde.build to remove committed .class files: https://github.com/eclipse-pde/eclipse.pde.build/pull/9
I thought it would be better to remove them immediately and not after the merge. Sorry for the extra work.

**Comment by vogella** [comment]
> > I can redo the merge work but would like to get confirmation from @vik-chand that he is fine with the merged history. @vik-chand can you check?
> 
> Thanks! Makes sense. Please note that I added another commit to pde.build to remove committed .class files: [eclipse-pde/eclipse.pde.build#9](https://github.com/eclipse-pde/eclipse.pde.build/pull/9) I thought it would be better to remove them immediately and not after the merge. Sorry for the extra work.

Thanks for this work on your side  and sorry for accidently adding these .class files.

**Comment by vogella** [comment]
As new commits have been done, I would have to do this again. So please use this as example to see if the master branch looks fine for and if not let me know. Otherwise I will redo the work beginning of next week and merge it relatively fast to avoid that is becomes obsolete again.

**Comment by ruspl-afed** [comment]
@vogella shouldn't we avoid adding bundles to the top level of repository? Perhaps they need to go to the `build` subfolder, WDYT?

**Comment by vogella** [comment]
> @vogella shouldn't we avoid adding bundles to the top level of repository? Perhaps they need to go to the `build` subfolder, WDYT?

I don't want to mix changes, so first the merge and afterwards a move if someone wants to do this. As Git calculates the history a move might result in loosing the history if you do too many things at the same time. I personally do not plan to move these projects, from the IDE perspective it does not matter there they are located.

**Comment by vogella** [comment]
I need the merge option for this one.

**Comment by vogella** [comment]
@vik-chand I think the project can enable merge commits in the settings. Can you check and enable this so that we can merge the two repos. If you do not have authentication I can open a help ticket

**Comment by vik-chand** [comment]
> I need the merge option for this one.

Enabled the merge option

**Comment by vik-chand** [comment]
> @vik-chand I think the project can enable merge commits in the settings. Can you check and enable this so that we can merge the two repos.

Done

**Comment by vogella** [comment]
Thanks, Vikas. The option can be disabled again.

**Comment by vik-chand** [comment]
> Thanks, Vikas. The option can be disabled again.

Done. Thanks for your work on this issue.

**Comment by HannesWell** [comment]
Thanks Lars. The change looks good.

**Pull request merged**
