### PR TITLE
Track whether the manifest of a bundle component has an explicit EE

### PR DESCRIPTION
**Pull request by merks**
https://github.com/eclipse-pde/eclipse.pde/issues/1283

### CODE REVIEW

**Comment by merks** [comment]
@iloveeclipse 

I've verified that this fixed the problem where the baseline version and the workspace version as the same and now both are validated such that both indicate they have no BREE and hence to BREE change:

image

Also verified that if I were to add an explicit BREE, this would be detected as a change to the BREE:

image

**Comment by merks** [comment]
@iloveeclipse 

I'll give some more time to review, but I'd like to commit this today so that I can update my IDE to fix the problem tomorrow....

**Review by iloveeclipse — APPROVED** [review]
Looks good for me and I also can confirm that the API error on Linux on SWT is gone with this patch.

**Comment by iloveeclipse** [comment]
> I'll give some more time to review, but I'd like to commit this today so that I can update my IDE to fix the problem tomorrow....

Sure. I've checked the patch on Linux, sounds reasonable, but I'm not that deep in this PDE code. I would say we should merge to get rid of the current (false positive) error on SWT and if the patch could be improved, it should be improved later.

**Pull request merged**
