### PR TITLE
Avoid NPE if JRE is missing #341

### PR DESCRIPTION
**Pull request by jukzi**
JavaRuntime.getExecutionEnvironmentsManager().getEnvironment(execEnvID) may return null

### CODE REVIEW

**Comment by HannesWell** [comment]
Looks good. Tahnks you.
Can you please apply that fix to `TargetPlatformHelper.bestVmInstallFor()` too? It can be called from `APIBaseline.initialize()` with a null environment too.

**Comment by jukzi** [comment]
611 failing tests https://github.com/eclipse-pde/eclipse.pde/issues/232

**Comment by HannesWell** [comment]
> 611 failing tests #232

Yep and a missing version bump for `org.eclipse.pde.core`

**Comment by HannesWell** [comment]
Thank you.

**Pull request merged**
