### PR TITLE
Spurious API tool error may occur if a new bundle added ( with same package as existing bundle)

### PR DESCRIPTION
**Pull request by vik-chand**
package as existing bundle)

### CODE REVIEW

**Comment by laeubi** [comment]
@vik-chand is this something we should merge now new stream is open?

**Comment by vik-chand** [comment]
> @vik-chand is this something we should merge now new stream is open?

thanks, I will merge it tomorrow after updating version

**Comment by vik-chand** [comment]
There are 359 test failures. I am looking at it.

**Comment by iloveeclipse** [comment]
@vik-chand : would you please rebase your branch on master instead of merging master into your branch?

@laeubi : we should add here same git checks like in the platform.

**Comment by vik-chand** [comment]
There were some issues in rebase - Created https://github.com/eclipse-pde/eclipse.pde/pull/520

I was able to recreate the test failures locally

**Pull request closed without merging**
