### PR TITLE
Refresh targets in the background

### PR DESCRIPTION
**Pull request by laeubi**
A target refresh operation is currently run in the UI thread as it probably in the past where considered a fast operation. At least with P2 Updatesites this is no longer the case and we can'T really make any valid assumptions on how other implementation might perform.

This now schedule the work into a background job and also cleanup the code to reflect current code base. In addition to that, if a job is already running, the user is asked to cancel it before perform other actions.

Fix https://github.com/eclipse-pde/eclipse.pde/issues/1523

### CODE REVIEW

**Comment by vogella** [comment]
During activator such a cancelation would also be nice, still possible to trigger activation multiple times white it is activating:

image

**Comment by vogella** [comment]
Otherwise, this is great. Works fine for me.

**Comment by vogella** [comment]
Would also be great to have the same for "Reload Target Platform" (similar to Activate).

**Comment by laeubi** [comment]
@vogella please create a dedicated issue with reproducer, I'm sure there are lingering other things around but we can only hunt them down one-by-one :-)

**Comment by laeubi** [comment]
Warnings are due to changing the Build to Java 21, I reset the quality gate now.

**Pull request merged**
