### PR TITLE
Update for release 4.28

### PR DESCRIPTION
**Pull request by laeubi**
@akurtakov FYI it seems I have had to create the PR manually as automatic creation failed with:

```
Create or update the pull request
  Attempting creation of pull request
  Error: GitHub Actions is not permitted to create or approve pull requests.
```

maybe the eclipse-releng bot needs additional permissions?

### CODE REVIEW

**Comment by laeubi** [comment]
@fredg02 can you check if the bot is allowed to create/update PRs for pde? It also seems the bot is not ECA compatible.

**Comment by fredg02** [comment]
Has this ever worked before?

**Comment by laeubi** [comment]
As this is the first time we try this new action, I would say there is no previous state to compare with :-D

**Comment by fredg02** [comment]
Can you point me to the action that created this commit?

**Comment by laeubi** [comment]
https://github.com/eclipse-pde/eclipse.pde/actions/runs/4291163959

**Comment by fredg02** [comment]
> Error: GitHub Actions is not permitted to create or approve pull requests.

This is caused by the option "Allow GitHub Actions to create and approve pull requests", explained here:
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#preventing-github-actions-from-creating-or-approving-pull-requests

After talking to the security team (@mbarbero) I've enabled this for the https://github.com/eclipse-pde org and all of its repos.

**Comment by iloveeclipse** [comment]
> After talking to the security team (@mbarbero) I've enabled this for the https://github.com/eclipse-pde org and all of its repos.

Shouldn't that be also done for Platform, JDT and Equinox repositories ?

**Comment by MohananRahul** [comment]
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/916

**Pull request merged**
