### PR TITLE
Ensure that ApiBuilderTest disables RUN_API_ANALYSIS_AS_JOB

### PR DESCRIPTION
**Pull request by merks**
Also ensure it initializes the ApiTestingEnvironment's target platform.

### CODE REVIEW

**Comment by merks** [comment]
@HannesWell @iloveeclipse 

Does this change look okay?  Are the GitHub Actions failures "normal"?

**Comment by HannesWell** [comment]
> @HannesWell @iloveeclipse
> 
> Does this change look okay? Are the GitHub Actions failures "normal"?

The GH workflow failure is not normal and they look like those currently on the master.
Nevertheless this change is very reasonable, thanks for your investigation and for Christoph's hint in https://github.com/eclipse-pde/eclipse.pde/pull/354#issuecomment-1406165679!
I have seen Jenkins pass in the past days sometimes, somay this was just lucky. But nevertheless I think this is an improvement and should be merged.

In general those tests should be migrated to Junit-4 or 5 (when/if that works in the Releng Build), but at least for me that would be a task for later.

**Comment by iloveeclipse** [comment]
> Does this change look okay? Are the GitHub Actions failures "normal"?

Yep, Rein damit!

**Review by HannesWell — APPROVED** [review]

**Comment by akurtakov** [comment]
As time consuming as it is moving tests to JUnit 4.x or even 5.x is best step for long term maintenance. Luckily it could be done step by step most of the time. I've been doing that when I look at some test for quite some time but help is more than welcome.

**Comment by merks** [comment]
Yes, only time will tell if the tests pass on Jenkins by luck or for real.

@laeubi  Thanks again for sharing your insight!

@akurtakov  The test extends org.eclipse.jdt.core.tests.builder.BuilderTests so that has to move first..

**Comment by laeubi** [comment]
> The test extends org.eclipse.jdt.core.tests.builder.BuilderTests so that has to move first..

and this extends [TestCase](https://github.com/eclipse-jdt/eclipse.jdt.core/blob/master/org.eclipse.jdt.core.tests.compiler/src/org/eclipse/jdt/core/tests/junit/extension/TestCase.java)
and this extend [PerformanceTestCase](https://github.com/eclipse-platform/eclipse.platform.releng/blob/master/bundles/org.eclipse.test.performance/src/org/eclipse/test/performance/PerformanceTestCase.java)
that finally extends (junit3)TestCase :-)

**Comment by akurtakov** [comment]
So many suboptimal and plain wrong things. To start with PerformanceTestCase should never make it to not performance tests to start with.

**Comment by laeubi** [comment]
What offered today by `PerformanceMeter` should today be a JUnit Rule maybe even something build in:
https://junit.org/junit4/javadoc/4.12/org/junit/rules/Stopwatch.html

**Comment by akurtakov** [comment]
I've opened https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/discussions/828 for the long term discussion about these perf tests as they have been plain useless for the last couple fo years.

**Pull request merged**
