### PR TITLE
Enable tycho.apitools.debug & disable DetectVMInstallationsJob

### PR DESCRIPTION
**Pull request by iloveeclipse**
This doesn't fix the problem, but may be gives some hints

See https://github.com/eclipse-pde/eclipse.pde/issues/888

### CODE REVIEW

**Comment by laeubi** [comment]
You need to add a change like in https://github.com/eclipse-pde/eclipse.pde/pull/887 or otherwise API check will be skipped.

**Comment by iloveeclipse** [comment]
> You need to add a change like in #887 or otherwise API check will be skipped.

I would like to merge it "as is" to master. Or does it break anything?

**Comment by laeubi** [comment]
> > You need to add a change like in #887 or otherwise API check will be skipped.
> 
> I would like to merge it "as is" to master. Or does it break anything?

It will just print more things to the log.

**Comment by iloveeclipse** [comment]
> It will just print more things to the log.

OK, so fine to merge then, that is exact the purpose of this PR...

**Comment by laeubi** [comment]
> OK, so fine to merge then, that is exact the purpose of this PR...

Nevertheless if we do not want **permanent** debug logging it might be better to include such temporal things in the affected PR...

**Comment by iloveeclipse** [comment]
> Nevertheless if we do not want **permanent** debug logging it might be better to include such temporal things in the affected PR...

Once we have solution for #888 we can revert this commit.

**Pull request merged**
