### PR TITLE
AbstractScriptGenerator.newAntScript: revert close stream #967

### PR DESCRIPTION
**Pull request by jukzi**
https://github.com/eclipse-pde/eclipse.pde/issues/967

### CODE REVIEW

**Review by HannesWell — APPROVED** [review]
Looks good. Lets see what the build says.

And thanks for the little code clean-up.

**Comment by iloveeclipse** [comment]
Interesting, same test fails as before? Does it work locally?

**Comment by jukzi** [comment]
it fixes SourceTests.testIndividualSourceBundles_2()  locally

**Comment by iloveeclipse** [comment]
> it fixes SourceTests.testIndividualSourceBundles_2() locally

So looks like https://github.com/eclipse-pde/eclipse.pde/pull/980 is testing something else (previous build?), not the current code in the PR?

The test fails in this PR are exactly same as in  https://github.com/eclipse-pde/eclipse.pde/pull/980

- https://ci.eclipse.org/pde/job/eclipse.pde/job/PR-984/3/testReport/junit/org.eclipse.pde.build.internal.tests/SourceTests/testIndividualSourceBundles_2/
- https://ci.eclipse.org/pde/job/eclipse.pde/job/PR-980/3/testReport/junit/org.eclipse.pde.build.internal.tests/SourceTests/testIndividualSourceBundles_2/

**Comment by iloveeclipse** [comment]
On the other side, there are not more test fails, so we should simply merge this one and see what the next build would say, **if** we will have the build tomorrow, see [this comment](https://github.com/eclipse-pde/eclipse.pde/pull/980#issuecomment-1841568266).

**Comment by laeubi** [comment]
> it fixes SourceTests.testIndividualSourceBundles_2() locally

I just wanted to mention that the tests seem to behave completely different in some cases between platforms and between being executed on Jenkins or I-Builds, its a bit messy.

**Pull request merged**
