### PR TITLE
Moving pde.build projects into a build folder

### PR DESCRIPTION
**Pull request by vogella**
PDE organizes its functionality around folder, so after the merge we
should also move the projects into a separate folder.

### CODE REVIEW

**Comment by vogella** [comment]
@ifedorenko as suggested by you  the project move. I don't know why the build fails, run fine locally.

**Comment by vogella** [comment]
@sravanlakkimsetti any idea what is wrong here? I would like to merge this, as this would allow us to configure the Javadoc build for the aggregator easier as build would be in a dedicated directory.

**Comment by sravanlakkimsetti** [comment]
The error message indicates compilation did not happen or the compiled class files are at completely different location than expected. 

Try running with debug options Also I would prefer having a pom.xml in pde.build plugin folder to understand the pom hierarchy(you can see this with m2e plugin in eclipse). This would be very useful while debugging this kind of errors

**Comment by vogella** [comment]
> The error message indicates compilation did not happen or the compiled class files are at completely different location than expected.

Works fine locally so I'm a bit lost

> Try running with debug options 

As the build does not fail locally, I don't see how this can help

> Also I would prefer having a pom.xml in pde.build plugin folder to understand the pom hierarchy(you can see this with m2e plugin in eclipse). This would be very useful while debugging this kind of errors

There is one, see https://github.com/eclipse-pde/eclipse.pde/pull/66/files#diff-5fbb42638c3d20d5a513da0fff2e8f3751bda2eb11f2ca08248c9c49f2a0c757

GH does not show the deleted "tests" project only the addition of it in the build folder, not sure why.

**Comment by sravanlakkimsetti** [comment]
I dont see a pom.xml inside. eclipse.pde/build/org.eclipse.pde.build folder. This pom will contain the actual paths used by the build. 

Can you please restore this pom for debugging?

**Comment by vogella** [comment]
> Can you please restore this pom for debugging?

Done

**Comment by sravanlakkimsetti** [comment]
I am getting the following error for the newly created pom.
Description	Resource	Path	Location	Type
Project build error: Non-resolvable parent POM for org.eclipse.pde:eclipse.pde.ui:4.24.0-SNAPSHOT: Could not find artifact org.eclipse:eclipse-platform-parent:pom:4.24.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM	pom.xml	/eclipse.pde	line 17	Maven pom Loading Problem

**Comment by merks** [comment]
I wonder, do that ant tasks like localbuild.xml still kick in.  Those might need adjusting.  There's quite a bit of funky stuff in the build.properties for building the ant stuff too...

**Comment by vogella** [comment]
@HannesWell if I reset to origin/master and pull in the request again I see all changes. Maybe the WebUI has issues with the "build" folder name?  I will try to use "builder".

**Comment by vogella** [comment]
@sravanlakkimsetti feel free to redo the change via another PR. AFAIK GH does not allow to update others PR. Unfortunately I have to step away from the laptop as I have to pickup the kids.

**Comment by sravanlakkimsetti** [comment]
here is the error I get locally
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-packaging-plugin:3.0.0-SNAPSHOT:package-plugin (default-package-plugin) on project org.eclipse.pde.build: Execution default-package-plugin of goal org.eclipse.tycho:tycho-packaging-plugin:3.0.0-SNAPSHOT:package-plugin failed: basedir C:\Users\018098744\git\eclipse.pde\build\org.eclipse.pde.build\target\classes does not exist -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.tycho:tycho-packaging-plugin:3.0.0-SNAPSHOT:package-plugin (default-package-plugin) on project org.eclipse.pde.build: Execution default-package-plugin of goal org.eclipse.tycho:tycho-packaging-plugin:3.0.0-SNAPSHOT:package-plugin failed: basedir C:\Users\018098744\git\eclipse.pde\build\org.eclipse.pde.build\target\classes does not exist
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:972)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-package-plugin of goal org.eclipse.tycho:tycho-packaging-plugin:3.0.0-SNAPSHOT:package-plugin failed: basedir C:\Users\018098744\git\eclipse.pde\build\org.eclipse.pde.build\target\classes does not exist
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:148)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	... 20 more
Caused by: java.lang.IllegalStateException: basedir C:\Users\018098744\git\eclipse.pde\build\org.eclipse.pde.build\target\classes does not exist
	at org.codehaus.plexus.util.DirectoryScanner.scan(DirectoryScanner.java:281)
	at org.eclipse.tycho.packaging.IncludeValidationHelper.checkDir(IncludeValidationHelper.java:105)
	at org.eclipse.tycho.packaging.IncludeValidationHelper.checkIncludesExist(IncludeValidationHelper.java:79)
	at org.eclipse.tycho.packaging.IncludeValidationHelper.checkBinIncludesExist(IncludeValidationHelper.java:46)
	at org.eclipse.tycho.packaging.AbstractTychoPackagingMojo.checkBinIncludesExist(AbstractTychoPackagingMojo.java:135)
	at org.eclipse.tycho.packaging.PackagePluginMojo.createPluginJar(PackagePluginMojo.java:240)
	at org.eclipse.tycho.packaging.PackagePluginMojo.execute(PackagePluginMojo.java:172)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	... 21 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :org.eclipse.pde.build

**Comment by sravanlakkimsetti** [comment]
while building pdebuild.jar and lib/pdebuild-ant.jar the basedir is set to <pde root>\build\org.eclipse.pde.build\target\classes but this folder doesn't get created. the classes are generated in <pde root>\build\org.eclipse.pde.build\target\pdebuild.jar-classes and <pde root>\build\org.eclipse.pde.build\target\lib\pdebuild-ant.jar-classes

I think we will need help from @vik-chand on how this build works.

**Comment by akurtakov** [comment]
This patch leaves pde.build.tests in the main dir.

**Comment by vogella** [comment]
> This patch leaves pde.build.tests in the main dir.

Did you pull in the request? I moved it and for me in my local file system it is moved. Also I did reset HEAD~1 hard and pull the change again and it was moved again for me

**Comment by akurtakov** [comment]
I looked here only. Will pull now to check.

**Comment by HannesWell** [comment]
EGit also says you are not moving some parts:
grafik





> > This patch leaves pde.build.tests in the main dir.
> 
> Did you pull in the request? I moved it and for me in my local file system it is moved. Also I did reset HEAD~1 hard and pull the change again and it was moved again for me

Resting does not delete untracked files. You have to clean your repo to really achieve this or delete the orphans in the old folder manually.

**Comment by HannesWell** [comment]
Ich think the problem is this git ignore:
grafik

I ignores everything that has 'temp' in its name (like 'template') and a `build.xml`.

**Comment by HannesWell** [comment]
So when you move the projects locally only the deletion part is tracked by git. The addition part at the new location is ignored due to the mentioned .gitignore.

**Comment by HannesWell** [comment]
Updating the o.e.pde.build/.gitignore with the following values fixed that for me locally:
```
temp*
!/templates/
build.xml
!/scripts/build.xml
```

Do you want to try that (could you then please use the name `build`, IMHO this fits better)? Or should I submit my change in another PR?

**Comment by HannesWell** [comment]
Created https://github.com/eclipse-pde/eclipse.pde/pull/67, lets see if the adjusted .gitignore helps.

**Comment by vogella** [comment]
FYI -  I can look at these things later today, but currently I'm in a client workshop and can't provide any change.

**Comment by vogella** [comment]
Done via https://github.com/eclipse-pde/eclipse.pde/pull/67 by @HannesWell Thanks Hannes

**Comment by vik-chand** [comment]
We got a new test failure. Possibly related to moving pde.build

https://github.com/eclipse-pde/eclipse.pde/issues/75

**Pull request closed without merging**
