### PR TITLE
remove unnecessary casts

### PR DESCRIPTION
**Pull request by stephan-herrmann**
When https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2471 is merged, ecj will signal more casts as unnecessary.

With this PR I suggest to remove affected casts before new errors/warnings will show up in the build.

### CODE REVIEW

**Comment by stephan-herrmann** [comment]
MacOS build is unhappy:

```
Error:  Failed to execute goal org.eclipse.tycho:tycho-apitools-plugin:4.0.8:verify (verify) on project org.eclipse.tools.layout.spy: Execute ApiApplication failed: InvocationTargetException: Component 'Layout Spy' in the baseline 'workspace' is disposed: Component was disposed here -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.tycho:tycho-apitools-plugin:4.0.8:verify (verify) on project org.eclipse.tools.layout.spy: Execute ApiApplication failed
```

@merks  any idea?

**Comment by akurtakov** [comment]
As long as Jenkins is fine it's good to go.

**Comment by stephan-herrmann** [comment]
> As long as Jenkins is fine it's good to go.

thanks!

**Comment by HannesWell** [comment]
Thanks for this PR.

> MacOS build is unhappy:
> 
> ```
> Error:  Failed to execute goal org.eclipse.tycho:tycho-apitools-plugin:4.0.8:verify (verify) on project org.eclipse.tools.layout.spy: Execute ApiApplication failed: InvocationTargetException: Component 'Layout Spy' in the baseline 'workspace' is disposed: Component was disposed here -
> ```

The baseline check is unfortunately flaky sometimes.

**Pull request merged**
