### PR TITLE
Test removing org.eclipse.rcp.configuration.feature.group

### PR DESCRIPTION
**Pull request by merks**
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2109

### CODE REVIEW

**Comment by merks** [comment]
@laeubi 

Surprisingly it seems all the tests pass!

@HannesWell 

The failures look like build/infrastructure problems, not test failures...

**Comment by laeubi** [comment]
Just be aware that removing it from `test.xml` will not be validated in a PR but at least for maven it looks like it works...

**Comment by merks** [comment]
I see.  Sort of but not really.  I see it referenced here:

image

So I assumed that tests just use it.  

What else uses this and when/where?  

This suggested there is no way to know without changing it and hoping for the best.   😨

**Comment by laeubi** [comment]
It is used by the I-Build: https://wiki.eclipse.org/Platform-releng/Eclipse_Test_Framework

the referenced one in code might or might not be *taht* `test.xml` as there are many of them...

**Review by HannesWell — APPROVED** [review]
Let's try if this works in I-builds.
If it fails, reverting it is overall simpler than thinking about it much longer.

**Comment by merks** [comment]
@iloveeclipse @akurtakov  @MohananRahul 

FYI, this change as some chance to break the I-Build via the PDE Build Test so I thought I'd give you a heads up...

**Comment by akurtakov** [comment]
Please start extra I build to test it.

**Comment by merks** [comment]
I've started https://ci.eclipse.org/releng/job/Builds/job/I-build-4.33/13/

**Comment by merks** [comment]
The build finished and I think it launched these tests:

image

But my knowledge of how this part works is poor.  😢

**Comment by merks** [comment]
If I'm reading the tea leaves correctly, only this JDT test is failing:

image

So am I safe to assume this change caused neither build nor test regressions?  Then I can proceed to remove what has no become an unused feature...

**Comment by iloveeclipse** [comment]
Yes, if you mean these tests: https://download.eclipse.org/eclipse/downloads/drops4/I20240611-0150/testResults.php I don't see "unexpected" new failures.

**Comment by merks** [comment]
@iloveeclipse 

Thanks for confirming!   That's very good news!  🎉

**Pull request merged**
