### PR TITLE
fix NPE in ApiBaseline.initialize #689

### PR DESCRIPTION
**Pull request by jukzi**
https://github.com/eclipse-pde/eclipse.pde/issues/689

### CODE REVIEW

**Comment by HannesWell** [comment]
@jukzi this isn't a regression from a recent change is it?

**Comment by jukzi** [comment]
probably not a recent regression

**Comment by HannesWell** [comment]
Ok.
The fix itself looks good and is straight forward. But I'm a bit concerend that it might cover a more fundamental problem.
I havn't encountered such issue yet, but with the emhanced system-package computation many special VM installs poped up that I didn't encountered either.

@akurtakov or the others what do you think? Should this be merged now or for the december release?

**Comment by merks** [comment]
It certainly can't break anything to prevent an NPE, and the NPE might prevent other valid things form working (like with saw with the DSL package for m3).

If you're concerned about masking problems (a legitimate concern) and the null is completely unexpected, you might add a warning/info log message too.

**Review by laeubi — APPROVED** [review]
looks good and is similar to other checks below.
Maybe it would even be better to have a `method putIfNotNull(dictonary, avalue)` on the long term...

**Review by HannesWell — APPROVED** [review]
> If you're concerned about masking problems (a legitimate concern) and the null is completely unexpected, you might add a warning/info log message too.

Yes that's my concern.
The method `PDEState.getSystemPackages()`, that produces the `value` (`TargetPlatformHelper.getSystemPackages()` just calls it), already issues a warning in that case :

https://github.com/eclipse-pde/eclipse.pde/blob/54ae301ae56ebfb1216db0dd0d4e124a49189c44/build/org.eclipse.pde.build/src/org/eclipse/pde/internal/build/site/PDEState.java#L498-L503

So I think this is good to go now.
And until the final submission of RC2 on friday we still have a few days to test I-builds.

**Review by merks — APPROVED** [review]
+1

**Comment by akurtakov** [comment]
Is it a regression in this release? In general this has to be brought to PMC for discussion. @theMcQ @vogella @tjwatson @jarthana  wdyt? 
To me it looks safe and worth pushing for this release.

**Comment by jukzi** [comment]
BTW there is no hurry for me to merge it. Today i am only producing pull commits to test the IDE :-)

**Comment by vogella** [comment]
+1 for merge from PMC member

Александър Куртаков ***@***.***> schrieb am Di., 29. Aug.
2023, 10:11:

**Pull request merged**
