### PR TITLE
Enable the Quality Gate

### PR DESCRIPTION
**Pull request by laeubi**
FYI @jukzi @vogella @akurtakov

### CODE REVIEW

**Review by HannesWell — APPROVED** [review]
Yes please.

**Comment by jukzi** [comment]
lets try

**Comment by vogella** [comment]
Hammer! Please also add this check to platform repos. Finally an automatic way to prevent warning creep

**Comment by laeubi** [comment]
> Hammer! Please also add this check to platform repos. 

As usually from then on each and every inconvenience with failing builds due to such quality checks are blamed on the messenger (aka committer of the config change) its unlikely I'll roll this out to the large, but the change is simple enough for anyone that finds it important enough for their project they fell confident enough to apply it anytime.

**Pull request merged**
