### PR TITLE
Fix regression in LaunchAction.concatArgs

### PR DESCRIPTION
**Pull request by HannesWell**
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/316

This is a regression from https://github.com/eclipse-pde/eclipse.pde/pull/288.

### CODE REVIEW

**Comment by HannesWell** [comment]
@vogella, @vik-chand I think we should merge this ASAP. Since this is a clear bug from me and the fix is trivial.

We need some approvals so late in the release cycle.

**Comment by akurtakov** [comment]
Could you add some test case for that?

**Comment by HannesWell** [comment]
In general yes, but I won't have time for that today.
So this should be merged without an extra Test, to have it available in 2022-09.

**Comment by akurtakov** [comment]
PMC approved.

**Comment by vogella** [comment]
Tested and fixes the reported issue.

Thanks @HannesWell for the fast fix.

**Comment by vogella** [comment]
@akurtakov I think we still have one build today for RC2, if not please trigger a rebuild.

**Comment by akurtakov** [comment]
There should be 2 more builds. Next one in 3h.

**Pull request merged**
