### PR TITLE
Startlevel & Autostart values are displaying in Run/Debug config #649

### PR DESCRIPTION
**Pull request by Dinesh0723**
Disposing the editor in tree viewer.

Fixes https://github.com/eclipse-pde/eclipse.pde/issues/649

### CODE REVIEW

**Comment by alshamams** [comment]
I have verified the changes made, and they are working. 👍

**Comment by gireeshpunathil** [comment]
@Dinesh0723 - could you please sign ECA? https://www.eclipse.org/legal/ECA.php

**Comment by Dinesh0723** [comment]
> @Dinesh0723 - could you please sign ECA? https://www.eclipse.org/legal/ECA.php

I have already signed the ECA form.
2023-10-27_09h53_39
.

**Comment by iloveeclipse** [comment]
> I have already signed the ECA form.

But you used different mail for that:

> Committer did not have a signed ECA on file. (130960675+Dinesh0723@us*rs DOT noreply DOT github DOT com)

Please use email in commit that was used for ECA.

**Comment by gireeshpunathil** [comment]
most probably your git shell / eclipse egit is not configured with your email.
`git config --global user.email <your email>`
`git config --global user.name <your name>`

and then push again probably should fix this.

**Comment by gireeshpunathil** [comment]
@Dinesh0723 - I see you have bit of tough time pushing changes. let me try to help you here.
 - `git fetch upstream` (assuming you have configured this remote as upstream)
 - `git rebase upstream/master`
 - in case of any conflicts resolve those manually
 - once all are clean, just do `git log` and see your one single commit is comfortably sitting on top of `upstream/master`
 - at that point you push to origin: `git push origin <the pr's branch name>` (btw, your branch name is pretty long, you can skim through other PRs to see a common naming convention for PR branches)
 
while all the above steps are for command line, I guess similar menu items will be there in eclipse edit as well.

feel free to ask if you get into trouble in any step!

**Comment by Dinesh0723** [comment]
@gireeshpunathil , This PR is messed up with multiple commits. I have tried the above steps as you mentioned that didn't worked. so, I am planning to close this PR and create a new PR for this issue.

**Comment by gireeshpunathil** [comment]
sorry @Dinesh0723 that this happened. But don't worry at all, I can help you resolve this through a quick zoom or Webex call, or if it is easy for you to do it in a new PR then go for that; whichever is convenient to you, let me know!

**Comment by Dinesh0723** [comment]
> sorry @Dinesh0723 that this happened. But don't worry at all, I can help you resolve this through a quick zoom or Webex call, or if it is easy for you to do it in a new PR then go for that; whichever is convenient to you, let me know!

Thanks for your support. I have already created a new PR (https://github.com/eclipse-pde/eclipse.pde/pull/931). I will contact you in future, if I am stuck.

**Pull request closed without merging**
