### PR TITLE
Adapt tests to migration to javax-bundles provided by Jakarta

### PR DESCRIPTION
**Pull request by HannesWell**
As mentioned in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1056#issuecomment-1541421660 the test needs adjustments.

### CODE REVIEW

**Comment by HannesWell** [comment]
@iloveeclipse FYI

**Comment by iloveeclipse** [comment]
Still failing :(
https://ci.eclipse.org/pde/job/eclipse.pde/job/PR-596/1/testReport/junit/AllPDEMinimalTests%20org.eclipse.pde.ui.tests.launcher.AllLauncherTests%20org.eclipse.pde.ui.tests.launcher/FeatureBasedLaunchTest/testGetMergedBundleMap_autostartLevels/

**Comment by HannesWell** [comment]
Strange.

> Still failing :(

Strange. According to the message the `javax.inject` bundle is still present and the in your PR https://github.com/eclipse-pde/eclipse.pde/pull/595 from earlier this day that test did not fail.
I have the impression that the old TP is still used. Maybe we wait for one more night and try again tomorrow?

**Comment by iloveeclipse** [comment]
Thanks, test is green again.

**Pull request merged**
