### PR TITLE
Bug 564563: Remove terminally deprecated pde.ui.launcher API

### PR DESCRIPTION
**Pull request by HannesWell**
Complete the API removal process after the two years waiting period is gone by.

The removal process was started with [Bug 564563](https://bugs.eclipse.org/bugs/show_bug.cgi?id=564563) exactly two years ago (believe it or not I did not had it in my calendar 😅), so according to the [API_Removal_Process](https://wiki.eclipse.org/Eclipse/API_Central/API_Removal_Process) we can finally remove it.

@jhonnen did you create some migration guide entries that now have to be moved to the removed API section according to the mentioned document:
`the API is removed and the porting guide entry is moved from the "Planned API removals" to the "Removed APIs" section in the documentation.`

### CODE REVIEW

**Comment by akurtakov** [comment]
@HannesWell This refers to https://github.com/eclipse-platform/eclipse.platform.common/blob/7a83e2b94ae3022a4e0e5e19b5f881a7203f4156/bundles/org.eclipse.platform.doc.isv/porting/removals.html#L158 being moved to a newly created "Removed APIs in the Eclipse 4.24 release:" section in the doc.

**Review by jhonnen — APPROVED** [review]
Thanks, Hannes!

**Comment by vogella** [comment]
Don't wait for me, I'm currenlty only super part time active, as I'm currently having to flght a mild case of corvid.

All deletions are good, so just merge. Please update the API removal guide.

**Comment by HannesWell** [comment]
> Don't wait for me, I'm currenlty only super part time active, as I'm currently having to flght a mild case of corvid.
> 
> All deletions are good, so just merge. Please update the API removal guide.

Actually it just slipped down my TODO list. Nevertheless get well soon. 👍🏽




> @HannesWell This refers to https://github.com/eclipse-platform/eclipse.platform.common/blob/7a83e2b94ae3022a4e0e5e19b5f881a7203f4156/bundles/org.eclipse.platform.doc.isv/porting/removals.html#L158 being moved to a newly created "Removed APIs in the Eclipse 4.25 release:" section in the doc.

Thanks Aleks!
Done this here: https://github.com/eclipse-platform/eclipse.platform.common/pull/43

Since the doc adjustment is prepared, this can be submitted.

**Pull request merged**
