### PR TITLE
Autocompletion support for some of the headers in pde.bnd file

### PR DESCRIPTION
**Pull request by alshamams**
This commit tries to add autocompletion suport for some of the headers in the pde.bnd file, such as compression, resolve and failok.
Ref: [817](https://github.com/eclipse-pde/eclipse.pde/pull/817)

### CODE REVIEW

**Comment by laeubi** [comment]
@alshamams thanks for you contribution, we have [recently added support for autocompletion already](https://github.com/eclipse-pde/eclipse.pde/pull/823), can you explain if you have issues that autocompletion does not work at all for you or if there is something specifically missing?

**Comment by alshamams** [comment]
> [recently added support for autocompletion already](https://github.com/eclipse-pde/eclipse.pde/pull/823)

Hi @laeubi ,
I started working on this long back before your PR landed, so I missed this one. I have checked and the autocompletion feature works well. Do you have any further work to suggest that can be added on top of your work?

**Comment by laeubi** [comment]
Okay, sorry about that!

Actually just use it, test it and if you feel something is missing ad support for it :-)

One thing I have thought about was with `-runee` and alike support autocomplete like for bundles ... but thats probably rare.

**Comment by HannesWell** [comment]
> > [recently added support for autocompletion already](https://github.com/eclipse-pde/eclipse.pde/pull/823)
> 
> Hi @laeubi , I started working on this long back before your PR landed, so I missed this one. I have checked and the autocompletion feature works well. Do you have any further work to suggest that can be added on top of your work?

@alshamams Sorry for the duplicated/unnecessary work, but with that knowledge, can we close this PR?

**Pull request closed without merging**
