### PR TITLE
Fixing broken code tags in Javadoc

### PR DESCRIPTION
**Pull request by alshamams**
The commit attempts to fix the broken code tags in Javadocs across various files in eclipse.pde.

Inspired by: #928

### CODE REVIEW

**Review by gireeshpunathil — APPROVED** [review]

**Comment by gireeshpunathil** [comment]
landing has to wait till the code freeze is lifted (12/07?)

**Review by HannesWell — APPROVED** [review]
> landing has to wait till the code freeze is lifted (12/07?)

Master is open now.

**Comment by jukzi** [comment]
> Master is open now.

beginner question: where can that be seen?

**Comment by iloveeclipse** [comment]
> > Master is open now.
> 
> beginner question: where can that be seen?

Please subscribe to https://www.eclipse.org/mailman/listinfo/platform-releng-dev mailing list.
See https://www.eclipse.org/lists/platform-releng-dev/msg39788.html

Or eclipse-dev, or platform-dev...

**Comment by jukzi** [comment]
> Please subscribe to https://www.eclipse.org/mailman/listinfo/platform-releng-dev mailing list.

done

**Pull request merged**
