### PR TITLE
Make the e4 view created by PDE template closable

### PR DESCRIPTION
**Pull request by vogella**
The currently contributed part is not closable which is not a typical
behavior for contributed parts.

### CODE REVIEW

**Comment by vogella** [comment]
Do we have a freeze  day today? I did not see an email for that.

**Comment by mickaelistria** [comment]
See https://calendar.google.com/calendar/embed?src=prfk26fdmpru1mptlb06p0jh4s%40group.calendar.google.com

**Comment by vogella** [comment]
@laeubi something seems wrong with the new API parser, works fine on GH action for Ubuntu but not on Windows.

**Comment by laeubi** [comment]
This sadly is an issue with:
- https://github.com/actions/upload-artifact/issues/240

so let the peoples there know this is an issue and ask for a fix :-)

**Comment by vogella** [comment]
> This sadly is an issue with:
> 
> * [`ENOENT: no such file or directory` while attempting to upload actions/upload-artifact#240](https://github.com/actions/upload-artifact/issues/240)
> 
> so let the peoples there know this is an issue and ask for a fix :-)

Not sure what the exact issue is, so I leave that to you as you worked on this. Maybe we should disable the verifcation GH build on Windows until this is fixed?

**Comment by laeubi** [comment]
> Not sure what the exact issue is, so I leave that to you as you worked on this. Maybe we should disable the verifcation GH build on Windows until this is fixed?

This currently only affects the upload of the test results, so I think it is still useful.

**Comment by HannesWell** [comment]
What's the status here? Can this be submitted?

**Comment by vogella** [comment]
> What's the status here? Can this be submitted?

Yes, IIRC tests were failing before but I think these were unrelated.

**Comment by merks** [comment]
I think normally there were 349 tests failing...

**Comment by akurtakov** [comment]
Just the "usual" test failures.

**Pull request merged**
