### PR TITLE
PrefereneGatherer from the spy.preferences can be static

### PR DESCRIPTION
**Pull request by vogella**
Save the reference to the outerclass.

### CODE REVIEW

**Comment by HannesWell** [comment]
Looks good.
But since you started to save references I suggest to pass the same `new PrefereneGatherer(preferenceEntries)` to `accept()` methods in `ShowAllPreferencesHandler.execute()`.

And actually you could convert the entire class `PrefereneGatherer` to a single lambda in `ShowAllPreferencesHandler.execute()`:

```
IPreferenceNodeVisitor gatherer = node ->{
 // code from PrefereneGatherer.visit()
}
bundleDefaultsScopePreferences.accept(gatherer);
configurationScopePreferences.accept(gatherer);
defaultScopePreferences.accept(gatherer);
instanceScopePreferences.accept(gatherer);
```
Maybe even inline all the four *ScopePreferences variables.

**Comment by akurtakov** [comment]
Any hope for this one to be finished?

**Comment by vogella** [comment]
@laeubi do we already have an issue for the Mac errors?

Error:  Failed to execute goal org.eclipse.tycho:tycho-apitools-plugin:4.0.0-SNAPSHOT:verify (verify) on project org.eclipse.pde.build: Execute the Api application failed! API Tools failure! -> [Help 1]
Error:  Failed to execute goal org.eclipse.tycho:tycho-apitools-plugin:4.0.0-SNAPSHOT:verify (verify) on project org.eclipse.pde.api.tools.annotations: Execute the Api application failed! API Tools failure! -> [Help 1]
Error:  Failed to execute goal org.eclipse.tycho:tycho-apitools-plugin:4.0.0-SNAPSHOT:verify (verify) on project org.eclipse.pde.junit.runtime: Execute the Api application failed! API Tools failure! -> [Help 1]
Error:  Failed to execute goal org.eclipse.tycho:tycho-apitools-plugin:4.0.0-SNAPSHOT:verify (verify) on project org.eclipse.ui.trace: Execute the Api application failed! API Tools failure! -> [Help 1]
Error:  Failed to execute goal org.eclipse.tycho:tycho-apitools-plugin:4.0.0-SNAPSHOT:verify (verify) on project org.eclipse.pde.spy.core: Execute the Api application failed! API Tools failure! -> [Help 1]
Error:  Failed to execute goal org.eclipse.tycho:tycho-apitools-plugin:4.0.0-SNAPSHOT:verify (verify) on project org.eclipse.pde.spy.bundle: Execute the Api application failed! API Tools failure! -> [Help 1]
Error:  Failed to execute goal org.eclipse.tycho:tycho-apitools-plugin:4.0.0-SNAPSHOT:verify (verify) on project org.eclipse.pde.spy.preferences: Execute the Api application failed! API Tools failure! -> [Help 1]
Error:  Failed to execute goal org.eclipse.tycho:tycho-apitools-plugin:4.0.0-SNAPSHOT:verify (verify) on project org.eclipse.tools.layout.spy: Execute the Api application failed! API Tools failure! -> [Help 1]

**Comment by laeubi** [comment]
> @laeubi do we already have an issue for the Mac errors?

Not a specific one but I'm working on it but if there is anyone with a real mac-machine to debug the startup problems any help would be appreciated :-)

**Comment by laeubi** [comment]
@vogella MAC test have now been improved, do you want to finish this before M1?

**Pull request closed without merging**
