### PR TITLE
Update commons.io in example product

### PR DESCRIPTION
**Pull request by laeubi**
Lets see if that works...

### CODE REVIEW

**Comment by HannesWell** [comment]
Since the PDE Product launcher as well as Tycho when building products adds all transitive dependencies by default it is actually sufficient to add the roots of the dependency graph to the product. So I suspect that many plug-ins can actually be removed.

**Comment by laeubi** [comment]
There is just one of the API tools failures so I think the test is fixed now, I leave it to @iloveeclipse if we should merge this...

**Comment by akurtakov** [comment]
This is weird as this PR changes the commons-io symbolic name to the Orbit one, so doesn't sound correct to me.

**Comment by laeubi** [comment]
@akurtakov I just started the SDK and used the commons IO that is provided by the target platform... and it seems the test itself is happy now...

**Comment by akurtakov** [comment]
No longer needed as commons-io is no longer explicitly listed.

**Pull request closed without merging**
