### PR TITLE
[API-Tools] Use JDT's JRT-FileSystem cache

### PR DESCRIPTION
**Pull request by HannesWell**
@merks you implemented to method in https://github.com/eclipse-pde/eclipse.pde/pull/357, do you have any objection?

### CODE REVIEW

**Comment by merks** [comment]
If using internals isn't a problem then it's fine.   (Of course that's why internals are not really so internal that one can assume changing them breaks no one.)

**Comment by HannesWell** [comment]
> If using internals isn't a problem then it's fine.   (Of course that's why internals are not really so internal that one can assume changing them breaks no one.)

We used `JRTUtil` in that meethod already before this change. 
And yes it's not ideal to use internals but I hope we are friends with JDT even though the api.tools plugin is not mentioned as such the manifest of the providing plugin.
And even if PDE is not notified in advance about a breaking change we will notice it latest in the next nightly I-Build.
Sharing the cache is IMO worth it.

**Comment by merks** [comment]
Note that I think it shares the cache either way because that sharing is what the JRE is providing.

**Comment by HannesWell** [comment]
> Note that I think it shares the cache either way because that sharing is what the JRE is providing.

I debuged through the creation of the JRT file-system with a JDK-17 and `jdk.internal.jimage.ImageReader` is indeed cached within the JDK already. I guess that's the heaviest thing? But still there are some more objects created without it. And as long as JDT also has a cache for the JRT-filesystems I think it is reasonable to reuse it instead of having our own. If caching not necessary at all we should remove it here and in JDT.

Then lets have this. Thank you for your explanations Ed.

**Pull request merged**
