### PR TITLE
Fix 'URI is not hierarchical' failure in PluginBasedLaunchTest

### PR DESCRIPTION
**Pull request by HannesWell**
Fixes https://github.com/eclipse-pde/eclipse.pde/issues/480.

In PluginBasedLaunchTest the test cases
- testTwoVersionsOfSameBundleBundlesInfo
- testTwoVersionsOfSameBundleConfigIni

failed on Windows (and probably similar on Mac) because the URL/URI value of the '-configuration' program argument is not correctly build. On windows it is something similiar to 'file:C:/path1/path2/' while it should be 'file:///C:/path1/path2/'.
This makes the test case resilient against this kind of malformed URL/URIs.

It is great that we now build on all platforms, which should prevent such failures in the future.

This also reminds me about https://github.com/eclipse-platform/eclipse.platform/issues/35.

### CODE REVIEW

**Comment by HannesWell** [comment]
Let's see if this also fixes the intermittent test failures in `Workspace(Product)ModelManagerTest`.
This would be a simple lucky punch that fixes multiple open issues. Locally on my computer the test succeeded like before.

**Comment by HannesWell** [comment]
> Let's see if this also fixes the intermittent test failures in `Workspace(Product)ModelManagerTest`. This would be a simple lucky punch that fixes multiple open issues. Locally on my computer the test succeeded like before.

There was now at least one successful pass. In case the change in this PR is really a fix this would fix the following issues:

- https://github.com/eclipse-pde/eclipse.pde/issues/21
- https://github.com/eclipse-pde/eclipse.pde/issues/125
- https://github.com/eclipse-pde/eclipse.pde/issues/255
- https://github.com/eclipse-pde/eclipse.pde/issues/300
- https://github.com/eclipse-pde/eclipse.pde/issues/375
- https://github.com/eclipse-pde/eclipse.pde/issues/359
- https://github.com/eclipse-pde/eclipse.pde/issues/494

**Comment by laeubi** [comment]
I don't see any of the "not hirachical" anymore so this this seems to work an we can merge this?!

**Comment by HannesWell** [comment]
> I don't see any of the "not hirachical" anymore so this this seems to work an we can merge this?!

I also added some more commits to investigate the test-failure in that class in the mac workflow that have to be adjusted. So this PR is not read for merge now. I will complete it this evening.

**Comment by HannesWell** [comment]
I now moved the part that aims to fix the WorkspaceManagerTests into https://github.com/eclipse-pde/eclipse.pde/pull/544 and focus in this PR on fixing `PluginBasedLaunchTest`.

**Comment by HannesWell** [comment]
Looks like there is an issue on Mac to detect the available VMInstalls. Running the folllowing snippted:
```
System.out.println("Install-types");
for (IVMInstallType installType : JavaRuntime.getVMInstallTypes()) {
	System.out.println("Name: " + installType.getName());
	System.out.println("id: " + installType.getId());
	for (IVMInstall vmInstall : installType.getVMInstalls()) {
		System.out.println("VM loc: " + vmInstall.getInstallLocation());
	}
}
```
Produces the following console output on Mac:
```
Install-types
Name: Standard VM
id: org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType
Name: Execution Environment Description
id: org.eclipse.jdt.launching.EEVMType
Name: Standard 1.1.x VM
id: org.eclipse.jdt.launching.Standard11xVMType
```
While for example on Linux it is:
```
Install-types
Name: Execution Environment Description
id: org.eclipse.jdt.launching.EEVMType
Name: Standard VM
id: org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType
VM loc: /usr/lib/jvm/temurin-17-jdk-amd64
Name: Standard 1.1.x VM
id: org.eclipse.jdt.launching.Standard11xVMType
```

And I'm relatively sure that this is the reason for the failure of the `PluginBasedLaunchTest` on Mac.
Of course it could be worked around somehow, but the problem seem to be fundamental to me.
@iloveeclipse can you tell if something has changed in JDT in this regard in the past? Or is this a set up mistake in the mac-runners?
Can anybody with access to a Mac computer debug that test case and tell if there is any issue?

**Comment by HannesWell** [comment]
For now I'll leave the mac-failures out of this PR and just stick with fixing the originally intended test-case. That's already something.
The mac-failures can be fixed in another PR if somebody can tell how.

**Comment by laeubi** [comment]
> Looks like there is an issue on Mac to detect the available VMInstalls.

see the following PR for background and mitigation:
- https://github.com/eclipse-platform/eclipse.platform/pull/390
- https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/211

**Pull request merged**
