### PR TITLE
Improve Onboarding Icon for PDE

### PR DESCRIPTION
**Pull request by BeckerWdf**
See: https://github.com/eclipse-pde/eclipse.pde/pull/582

### CODE REVIEW

**Comment by iloveeclipse** [comment]
I personally like older better, but if someone feels the old isn't good for whatever reason, also OK with the new one.

**Comment by HannesWell** [comment]
Thanks @BeckerWdf for your work on the icons.

Personally I like the new ones more than the ones before, but think that the ones from https://github.com/eclipse-pde/eclipse.pde/pull/582#issuecomment-1543542297 are a bit more unobtrusive and therefore tend to like them most.

Sorry for the third opinion, but discussions about style questions are often highly influenced by personal taste and therefore patience is required.

**Comment by BeckerWdf** [comment]
> Thanks @BeckerWdf for your work on the icons.
> 
> Personally I like the new ones more than the ones before, but think that the ones from [#582 (comment)](https://github.com/eclipse-pde/eclipse.pde/pull/582#issuecomment-1543542297) are a bit more unobtrusive and therefore tend to like them most.
> 
> Sorry for the third opinion, but discussions about style questions are often highly influenced by personal taste and therefore patience is required.

So you like the version that doesn't have an outline. I think the outline has the advantage, that it's more clearly visible that the right part (the plug) is plugged *into* the left part (the outlet).

Would it be anyway ok for you to take the version with the outline?

**Review by HannesWell — APPROVED** [review]
> @HannesWell: Would it be anyway ok for you to take the version with the outline?

Yes I'm also fine with the outlined version.

**Comment by BeckerWdf** [comment]
Can some PDE commit then pls. commit this change?

**Comment by BeckerWdf** [comment]
> > Can some PDE commit then pls. commit this change?
> 
> Sure. Thanks again.
> 
> I really like the on-boarding story.
> 
> Btw. is there some new&noteworthy entry planned about how to implement custom ones?

Yes. I have that on my list.

**Comment by BeckerWdf** [comment]
> I really like the on-boarding story.

Thanks

**Comment by BeckerWdf** [comment]
> [HannesWell](/HannesWell)

@HannesWell: See https://github.com/eclipse-platform/www.eclipse.org-eclipse-news/pull/99

**Pull request merged**
