### PR TITLE
Bug 571101: ApiAnalysisApplication - add support for p2-repo baseline and clean up API-Application

### PR DESCRIPTION
**Pull request by HannesWell**
This PR resolves [Bug 571101](https://bugs.eclipse.org/bugs/show_bug.cgi?id=571101)

It was first addressed in [Eclipse Gerrit Change 176109](https://git.eclipse.org/r/c/pde/eclipse.pde.ui/+/176109) and [Gerrit Change 176108](https://git.eclipse.org/r/c/pde/eclipse.pde.ui/+/176108), both were abandoned because they were not completed at the time of the move to GH.

The first commit has to be tested if the new way of printing the API analysis result works well and for the second commit a corresponding UI to defined a P2 repo as API baseline directly is still missing.

### CODE REVIEW

**Comment by vogella** [comment]
That feature will be nice as it  will remove the need to download the SDK for setting up the API baseline. Thanks for working on this @HannesWell

**Comment by merks** [comment]
> That feature will be nice as it will remove the need to download the SDK for setting up the API baseline. Thanks for working on this @HannesWell

The Oomph setups already remove that need.  And because they reuse the shared bundle pool, setting up the API baseline takes just seconds.

**Comment by HannesWell** [comment]
> > That feature will be nice as it will remove the need to download the SDK for setting up the API baseline. Thanks for working on this @HannesWell
> 
> The Oomph setups already remove that need. And because they reuse the shared bundle pool, setting up the API baseline takes just seconds.

That's right. I also mentioned this in the discussion at [the initial Gerrit](https://git.eclipse.org/r/c/pde/eclipse.pde.ui/+/176109).
The associated Bug was created with the intention to only improve the `ApiAnalysisApplication` with the goal to simplify the setup in the Maven/Tycho build, nevertheless Mickael suggested to add corresponding UI support even if Oomph provides similar/better support for this.

**Comment by HannesWell** [comment]
> @HannesWell is this still interesting?

Not anymore.

**Pull request closed without merging**
