### PR TITLE
Check getBundle returns non-null after PDE Manifest-editor opened.

### PR DESCRIPTION
**Pull request by peddaiahjuturu**
### Bug description
(Regression introduced by https://github.com/eclipse-pde/eclipse.pde/pull/949 and reported in https://github.com/eclipse-pde/eclipse.pde/issues/864)
After opening MANIFEST.MF file in PDE Manifest-editor and delete the project, ll get NPE.

### CODE REVIEW

**Comment by peddaiahjuturu** [comment]
@HannesWell , @laeubi , @alshamams , i can`t add reviewers for this PR. can you guys review it.
Note: legal agreement check is failing with "Author Eclipse account cannot be found" issue.

**Comment by merks** [comment]
Will will need to get an ECA in place:

https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md#setting-up-your-eclipse-and-github-account

**Comment by peddaiahjuturu** [comment]
I`m closing this PR and create new PR with primary email id.

**Comment by HannesWell** [comment]
> I`m closing this PR and create new PR with primary email id.

You can always force-push amended commits to the branch of a Pull-Request. And while amending a commit you can also change the author/commiter mail.
So there is no need to close a PR and create a new one, just to fix an email, message or alike. :)

**Pull request closed without merging**
