### PR TITLE
Add minimalistic PDE onboarding properties.

### PR DESCRIPTION
**Pull request by vogella**
Onboarding image will be added via separate commit. For #557

### CODE REVIEW

**Comment by vogella** [comment]
Hey, now only Windows fails, so that merge......
Thanks @laeubi for fixing the Mac tests.

**Comment by HannesWell** [comment]
Aren't we in a freeze period since the M1 freeze was yesterday 12pm?
I wonder why the freeze check did not indicate this.

**Comment by vogella** [comment]
> Aren't we in a freeze period since the M1 freeze was yesterday 12pm? I wonder why the freeze check did not indicate this.

I trusted the freeze check. :-o

**Comment by laeubi** [comment]
oooops... I think Hannes is right and reminds me on:

- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/discussions/863#discussioncomment-5497686

**Comment by HannesWell** [comment]
> > Aren't we in a freeze period since the M1 freeze was yesterday 12pm? I wonder why the freeze check did not indicate this.
> 
> I trusted the freeze check. :-o

There is a typo in the calendar event :/
https://github.com/eclipse-pde/eclipse.pde/pull/559#issuecomment-1495736454

**Pull request merged**
