### PR TITLE
Trying to understand PDE test fails in Jenkins...

### PR DESCRIPTION
**Pull request by iloveeclipse**
The implicit types resolving for "var" seem to not work properly on
Jenkins, may be due different compilation settings / dependencies used?

See https://github.com/eclipse-pde/eclipse.pde/issues/232

### CODE REVIEW

**Comment by mickaelistria** [comment]
Do a local build with `mvn clean verify -Pbuild-individual-bundles` reproduce the issue?

**Comment by laeubi** [comment]
I have created https://github.com/eclipse/tycho/issues/1197 as it seems there is some check missing in Tycho...

**Comment by mickaelistria** [comment]
One approach is to compare the list of bundles listed in <testModule>/target/work/configuration/config.ini with the ones that are part of the launch configuration, and progressively try to make the launch configuration as close as possible from Tycho one until it becomes clear which bundle is in the PDE launch that is missing in Tycho execution.

**Comment by laeubi** [comment]
@iloveeclipse I also see a lots of:

```
 java.nio.file.NoSuchFileException: eclipse.pde/ui/org.eclipse.pde.core/target/ant_tasks/pde-ant.jar-classes
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1264)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
	at org.eclipse.jdt.internal.compiler.batch.ClasspathJar.initialize(ClasspathJar.java:201)
	at org.eclipse.jdt.internal.compiler.batch.ClasspathMultiReleaseJar.initialize(ClasspathMultiReleaseJar.java:38)
	at org.eclipse.jdt.internal.compiler.batch.FileSystem.<init>(FileSystem.java:235)
	at org.eclipse.jdt.internal.compiler.batch.Main.getLibraryAccess(Main.java:3495)
	at org.eclipse.jdt.internal.compiler.batch.Main.performCompilation(Main.java:4741)
	at org.eclipse.jdt.internal.compiler.batch.Main.compile(Main.java:1802)
```


what is somewhat expected as this is a folder, I'm just wondering if JDT requires a jar file?

**Comment by iloveeclipse** [comment]
> what is somewhat expected as this is a folder, I'm just wondering if JDT requires a jar file?

That's a bug. I have a fix, but that would most likely break the build...

**Comment by iloveeclipse** [comment]
> eclipse.pde/ui/org.eclipse.pde.core/target/ant_tasks/pde-ant.jar-classes

We should fix that, where is this - in maven/tycho/build properties?

**Comment by laeubi** [comment]
> That's a bug. I have a fix

In the compiler?

> but that would most likely break the build...

I'm already wondering why the build succeeds, I though it should fail the compilation in such cases?



> We should fix that, where is this - in maven/tycho/build properties?

Platform uses a crude combination of tycho, maven, and buildproperties declaring subjars to be build, and every time I ask it says **OH NO WE NEED THAT** this particular one is:
https://github.com/eclipse-pde/eclipse.pde/blob/6e1939b8018f40edb8c2c3d11493a734e9c1452a/ui/org.eclipse.pde.core/build.properties#L32

but there are man other places as well!

**Comment by iloveeclipse** [comment]
> this particular one is:

I don't see ant_tasks/pde-ant.jar**-classes** anywhere. Where and how is that "-classes" thing passed to ECJ?

**Comment by iloveeclipse** [comment]
I guess org.sat4j.core.jar is referenced in a MANIFEST.MF somewhere, but not as required bundle but in "Class-Path" attribute. I believe JDT scans that and automagically adds everything it can find there to the classpath.

**Comment by laeubi** [comment]
Yes I created
- https://github.com/eclipse-jdt/eclipse.jdt.core/issues/261

**Comment by laeubi** [comment]
I really don't get it...

- https://ci.eclipse.org/pde/job/eclipse.pde.ui/job/PR-231/5/ (on top of master) **succeeds**
- https://ci.eclipse.org/pde/job/eclipse.pde.ui/job/master/107/ (now merged) **fails**

**Comment by laeubi** [comment]
@merks do you know about the baseline stuff? The tests complain about:

> The project was not found in the workspace baseline: bundle.a

I also enabled stack traces so we can better see where things are going wrong:

- https://github.com/eclipse-pde/eclipse.pde/pull/241

**Comment by merks** [comment]
@laeubi No, sorry, I've never looked at the implementation details around that.

**Comment by mickaelistria** [comment]
As mentioned in https://github.com/eclipse-pde/eclipse.pde/issues/232#issuecomment-1197797747 , you don't need Jenkins to reproduce and debug the issue. Testing can more efficiently be done locally and you could even plug in the debugger.
So I think it'd be better to close this draft PR and keep discussing of progress (including "I tried X, it didn't work') on the ticket rather than scattering the discussion.

**Comment by mickaelistria** [comment]
Now working as expected.

**Pull request closed without merging**
