### PR TITLE
Add support for loading the baseline from a file that list bundles

### PR DESCRIPTION
**Pull request by laeubi**
Currently the ApiAnalysisApplication only accepts atarget that then is resolved and afterwards transformed in a list of files.

This change add support for passing a list of bundles directly to prevent this kind of indirection and save workload if the caller already knows the list of bundles (e.g. Tycho).

### CODE REVIEW

**Comment by laeubi** [comment]
@akurtakov would you mind triggering an I-build? Because of how API Tools works today one can only reliable verify/test this with a new ibuild repository.

**Comment by akurtakov** [comment]
Could you trigger one youself ? https://ci.eclipse.org/releng/job/Builds/job/I-build-4.28 . Let me know if you can't so I give you access .

**Comment by laeubi** [comment]
I triggered it know, just not sure if "everyone" can/should trigger an build, but I interpret your answer as you have no concerns :-)

**Comment by akurtakov** [comment]
We should trust each other to the sensible thing - wait a bit if build is close to finish or kill a just started build and etc. but it's a matter of common sense from the committer. Personally I believe that if someone is trusted to push code to the repo that one should be trusted to deal with builds too :smile:

**Pull request merged**
