### PR TITLE
Use ExtensionBasedTextEditor as the base instead of TextEditor

### PR DESCRIPTION
**Pull request by laeubi**
Actually all PDE source pages can benefit from Generic Editor also some functionality relies on the PDESourcePage as a base.

This makes the PDESourcePage extend the ExtensionBasedTextEditor to account for this.

### CODE REVIEW

**Comment by HannesWell** [comment]
> Actually all PDE source pages can benefit from Generic Editor also some functionality relies on the PDESourcePage as a base.

Can you please name the concrete benefits?

**Comment by laeubi** [comment]
> > Actually all PDE source pages can benefit from Generic Editor also some functionality relies on the PDESourcePage as a base.
> 
> Can you please name the concrete benefits?

In the "classic" Texteditor everything has to be provided by code, the Generic Editor instead works on extensions what can be provided even by third party plugins:

grafik

One quite complex example are language servers, lsp4e provide several things based on the LanguageServerProtocol (e.g. autocompletions) therefore one can plugin LSPs into arbitrary editors (if the use the Generic Editor Framework), PDE already do this with `org.eclipse.pde.genericeditor.extension` for the target editor.

**Comment by laeubi** [comment]
Another example is that we now can replace `org.eclipse.pde.internal.ui.editor.build.BuildSourceViewerConfiguration` by extension points to generic editor.

**Comment by mickaelistria** [comment]
IIRC, by default, the Generic Editor brings some features that are not in the default text editor, such as matching bracket highlight/jump; some default completion based on words already existing in the docs or other basic things like that which comes for free. But as @laeubi mentions, the benefit is that is becomes much much easiler to enrich the editors with simple extensions now.

**Pull request merged**
