### PR TITLE
Remove rarely usable Drag&Drop of EEs in Manifest-Editor Overview page

### PR DESCRIPTION
**Pull request by HannesWell**
Drag&drop support was introduced via [Bug 192890](https://bugs.eclipse.org/192890), but only supports reordering of required Execution-Environments in the same Plug-in project.
Because in the vast majority of cases Plug-ins only have one EE defined that feature is only rarely usable. And if a Plug-in project really defines multiple BREEs the Manifest Editor already provides an alternative with the 'Up' and 'Down' buttons next to the table.

grafik

While being only rarely usable support D&D support for required EEs makes it more difficult to support OSGi EE requirements in https://github.com/eclipse-pde/eclipse.pde/pull/1318.
Therefore I propose to remove it.

@laeubi, @merks or anbody else, do you have any objections?

### CODE REVIEW

**Comment by merks** [comment]
There are many places where drag and drop would be nice for reordering but this  seems at the very bottom of the list of useful places. 👍

**Comment by HannesWell** [comment]
> There are many places where drag and drop would be nice for reordering but this seems at the very bottom of the list of useful places. 👍

Absolutely.
Let's give other some time to react, but if there are no objections until tomorrow evening, I'll submit this.

**Comment by laeubi** [comment]
I don't even think the order matters at all, so maybe we can even remove the buttons...

**Comment by vogella** [comment]
+1 for removing DND here.

**Comment by HannesWell** [comment]
> I don't even think the order matters at all, so maybe we can even remove the buttons...

See https://github.com/eclipse-pde/eclipse.pde/pull/1324.

**Pull request merged**
